ALTER TABLE peminjaman
ADD CONSTRAINT fk_anggota FOREIGN KEY (id_anggota) REFERENCES anggota(id_anggota) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE peminjaman
ADD CONSTRAINT fk_buku FOREIGN KEY (id_buku) REFERENCES buku(id_buku) ON DELETE CASCADE ON UPDATE CASCADE;
